export const metadata = {
  title: 'Terms of Use – SkillBun',
  description: 'SkillBun terms of use — rules for using our platform.',
};

export default function TermsPage() {
  return (
    <div className="static-page">
      <h1>Terms of Use</h1>
      <p><em>Effective date: May 3, 2026</em></p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or registering on SkillBun, you agree to comply with and be bound by these Terms of Use. If you do not agree to the complete extent of this agreement, please refrain from using or accessing our platform. You accept responsibility for safeguarding your Google or email sign-in credentials.
      </p>

      <h2>2. Service Description</h2>
      <p>
        SkillBun provides an integrated suite of AI-assisted career discovery tools for technology students. The core services currently include profile onboarding, adaptive quiz recommendations, an AI counsellor chat (Bun-Bot), and interactive learning roadmaps visualizing career branches.
      </p>

      <h2>3. Educational Use & AI Acknowledgement</h2>
      <p>
        The responses, recommendations, and roadmaps generated by SkillBun (including those produced by Bun-Bot and the quiz engine) are intended <strong>strictly for educational and informational purposes</strong>. Language models can hallucinate or produce outdated technical knowledge. You acknowledge that SkillBun does not establish an advisory or professional relationship and does not guarantee admissions, placements, internships, salary outcomes, or the absolute correctness of any output.
      </p>

      <h2>4. Acceptable Use and User Responsibilities</h2>
      <p>
        You agree to engage with SkillBun in a manner that aligns with our educational objectives. You must not:
      </p>
      <ul>
        <li>Provide materially false profile information to bypass functionality limitations.</li>
        <li>Submit highly sensitive, confidential, or proprietary information, including API keys or PII beyond what is requested, in the free-text prompts of Bun-Bot.</li>
        <li>Attempt to reverse-engineer, decompile, scrape, or systematically mine data, schemas, or source code from our platform.</li>
        <li>Bypass technical limits, overload the servers, or probe for vulnerabilities through automated or manual tools.</li>
      </ul>

      <h2>5. Security, Validation, and Rate Limits</h2>
      <p>
        To ensure a fair and abuse-free environment, SkillBun enforces rate limits on interactions (e.g., chat sessions, quizzes). We monitor traffic utilizing server-side content validation and active human-verification checks (e.g., Cloudflare Turnstile token validation). Repeated violations or automated bot-like activity may result in temporary throttling or permanent suspension of your account without prior notice.
      </p>

      <h2>6. Third-Party Infrastructures</h2>
      <p>
        SkillBun operates using established third-party services: Google Gemini (for processing AI models), Firebase Authentication (for Google and email sign-in), Cloudflare Turnstile (for bot mitigation), and Cloud Firestore (for profile and roadmap-progress storage). Interaction with these providers is also governed by their respective Terms of Service. Their availability, latencies, and underlying policies remain outside SkillBun's direct control.
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        The SkillBun wordmark, logo, "bunny" visual motifs, source code, aggregated roadmaps schemas, platform branding, and UI/UX are the intellectual property of SkillBun and its creators (Team SkillBun). You may use the outputs of our service for your personal career advancement, but you may not reproduce, resell, repackage, or distribute substantial parts of our platform for commercial gain without explicit written authorization.
      </p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>
        SkillBun provides the platform on an "as is" and "as available" basis. To the maximum extent permitted by applicable laws in India, we expressly disclaim all warranties—whether express, implied, or statutory—including implied warranties of merchantability, fitness for a specific career outcome, and non-infringement.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        Under no legal theory shall Team SkillBun, its members, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages (including lost tuition fees, lost opportunity, or data loss) resulting from your reliance on, or inability to use, our platform. In a jurisdiction where exclusion of certain damages is prohibited, our liability is restricted to the highest degree permitted by law.
      </p>

      <h2>10. Suspensions and Modifications</h2>
      <p>
        We reserve the right to continually iterate, modify, or deprecate features of SkillBun to keep the ecosystem relevant. We may update these Terms to reflect product maturation or legal requirements. Material updates will be indicated by the "Effective Date" at the top of this page. Your continued use of SkillBun constitutes acceptance.
      </p>

      <h2>11. Contact & Legal Disputes</h2>
      <p>
        If you have concerns about the implementation of these Terms, need to report abuse, or wish to clarify your responsibilities, you may contact: <a href="mailto:harsh@skillbun.tech">harsh@skillbun.tech</a>
      </p>
    </div>
  );
}
